### ISSUE TITLE
What is the license assigned to this template?

### ISSUE THREAD

**Issue by derrxb** [web3templates/stablo#18]
Hi @surjithctly,

First of all, thank you for building this awesome template! I wanted to ask about the license attached to this template. https://web3templates.com/templates/stablo-minimal-blog-website-template it mentions that it's free to download/use & it comes with no additional support. 

Does this mean we're able to freely use this template as long as we don't expect any support? 

Derrick

**Comment by surjithctly** [comment]
Hello,

Added GNU License. See: https://github.com/web3templates/stablo/blob/main/LICENSE

You will be free to use.

**Comment by derrxb** [comment]
Thank you! 🙏🏽
