### ISSUE TITLE
Category 404ing

### ISSUE THREAD

**Issue by GazTheDev** [web3templates/stablo#24]
Hello, 

Noticed a bug, the categories URL is outputting a 404 page :). 

Many Thanks,

**Comment by surjithctly** [comment]
Hey,

The category page is a Pro feature. Available here: https://stablo-pro.web3templates.com/

I've made the changes to remove the broken link to # in the free version. 

fixed on this commit https://github.com/web3templates/stablo/commit/9a7e07cdc00dbeae429c213aea8eb4b687929144
