### ISSUE TITLE
sanity code-input

### ISSUE THREAD

**Issue by Raqibnur** [web3templates/stablo#32]
Please add sanity code-input support

**Comment by surjithctly** [comment]
Its supported in the Pro version. Do you think it needs to be in the free version as well?

**Comment by Raqibnur** [comment]
It's up to you, but I think it should be available in both versions.

**Comment by GustavoContreiras** [comment]
Such a great work. I'll probably implement the markdown text editor by myself using the free version.

**Comment by surjithctly** [comment]
Closed in favour of v2 release.
