### ISSUE TITLE
Unable to update Site Config from Sanity Studio

### ISSUE THREAD

**Issue by gburgi** [web3templates/stablo#35]
Hi, I just deployed  Stablo Free version to Vercel (on-click deploy).

When I try to edit de Site Config, every field is read-only. I don't understand why... Did I miss something?
<img width="1255" alt="image" src="https://user-images.githubusercontent.com/960197/212930743-4098eab8-6e1d-42ee-80bf-479700c4427f.png">

Thanks!

**Comment by surjithctly** [comment]
Could you disable the experimental actions line in the siteConfig.js in schemas? and try to add content first. Then re-enable the line.

**Comment by gburgi** [comment]
Thank you, that work for me!
