### ISSUE TITLE
Feature Request: Related Post / more post from this author

### ISSUE THREAD

**Issue by snowmanstudio** [web3templates/stablo#4]
Please Add Related Post/ You Might Also Like / more post from autor .....

Every Blog Need Related Post widgets ..... hope you will add this in next update

**Comment by snowmanstudio** [comment]
how much?

**Comment by surjithctly** [comment]
I did not decide yet. But it could be anywhere between $19-$39. 

I have planned multiple home page variations, blog search, tags, author pages, category pages, subscribe section, Relates posts as you've suggested and more..

**Comment by surjithctly** [comment]
Hey,

The Pro version is live now. It's priced at **$49**

Demo: https://web3templates.com/preview/stablo
Details & Download: https://web3templates.com/templates/stablo-minimal-blog-website-template

And if you need a special discount, email me or reach me on twitter :)

Thanks a lot. 

~Surjith
