### ISSUE TITLE
Error: Configuration must contain `projectId`

### ISSUE THREAD

**Issue by raphaeltm** [web3templates/stablo#45]
Fresh install on Vercel produces the following error:

```
Error: Configuration must contain `projectId`
    at t.initConfig (/studio/static/js/app.bundle.js?6cea117ad1f1fb7fee4a:109:4401)
    at x.config (/studio/static/js/app.bundle.js?6cea117ad1f1fb7fee4a:92:186312)
    at new x (/studio/static/js/app.bundle.js?6cea117ad1f1fb7fee4a:92:185648)
    at x (/studio/static/js/app.bundle.js?6cea117ad1f1fb7fee4a:92:185631)
    at Object. (/studio/static/js/app.bundle.js?6cea117ad1f1fb7fee4a:92:183290)
    at l (/studio/static/js/vendor.bundle.js?570c84d697b0399dba05:1:410)
    at Object. (/studio/static/js/app.bundle.js?6cea117ad1f1fb7fee4a:26:10206)
    at l (/studio/static/js/vendor.bundle.js?570c84d697b0399dba05:1:410)
    at Object. (/studio/static/js/app.bundle.js?6cea117ad1f1fb7fee4a:33:234749)
    at l (/studio/static/js/vendor.bundle.js?570c84d697b0399dba05:1:410)
```

Seems like the project gets deployed with this `sanity.json`:

```
{
  "root": true,
  "project": {
    "name": "Stablo Template",
    "basePath": "/studio"
  },
  "api": {
    "projectId": "",
    "dataset": "production"
  },
  "plugins": [
    "@sanity/base",
    "@sanity/default-layout",
    "@sanity/default-login",
    "@sanity/desk-tool",
    "asset-source-unsplash"
  ],
  "env": {
    "development": {
      "plugins": [
        "@sanity/vision"
      ]
    }
  },
  "parts": [{
      "name": "part:@sanity/base/schema",
      "path": "./schemas/schema"
    },
    {
      "implements": "part:@sanity/desk-tool/structure",
      "path": "./src/deskStructure"
    }
  ]
}
```

I'm not familiar with Sanity and just helping a friend out, but presumably that should be filled in with the appropriate projectId at build time? I tried manually replacing it and it works fine.

**Comment by surjithctly** [comment]
While you created the deployment have you installed sanity app in vercel? Then .env variables would fill in automatically.

For now, you can just manually add `.env` variable as shown in the `.env.example` file.

**Comment by pzagor2** [comment]
I get the same error. These are the `.env` variables created in Vercel automatically. 
![Screenshot 2023-03-23 at 06 40 44](https://user-images.githubusercontent.com/1126020/227113871-fde4702b-679f-4fd7-aee3-378009d53171.png)

**Comment by gilliantguo** [comment]
You need input your id here
"api": {
    "projectId": "HERE",
    "dataset": "production"

**Comment by gilliantguo** [comment]
AND Why I can't change the content of the site config, it is read-only
![image](https://user-images.githubusercontent.com/32230893/228281410-3e1f6a2f-fcc5-46c2-8d32-b47958ce5f20.png)

**Comment by surjithctly** [comment]
@gilliantguo Open `/studio/schemas/siteConfig.js` and comment out the following lines:

```
  __experimental_actions: [
    /* "create", "delete", */ "update",
    "publish"
  ],
```

Now, Add the content. Once added, make sure you re-added this again to avoid duplication since you wanted that to be singleton.

**Comment by surjithctly** [comment]
@raphaeltm for now, I suggest to add the project id in the `sanity.json` manually.

**Comment by surjithctly** [comment]
Thank you. I'm aware of the problem and will be address in v2 (already in development).

**Comment by surjithctly** [comment]
It should be fixed in v2 release.
