### ISSUE TITLE
generateMetadata inside Layout - empty params

### ISSUE THREAD

**Issue by alainkaiser** [web3templates/stablo#47]
Hi :) 

I am wondering how you could get your metadata solution to work? Basically, I am using the same approach to generate dynamic metadata inside the layout.tsx file as my metadata content is saved inside a cms. To fetch the the metadata settings, I need the current page route path as you do in your example, but the "params" for the function generateMetadata are always empty on my end.

Your example looks like this:
```
export async function sharedMetaData(params) {
  const settings = await getSettings();

  return {
    // metadataBase: new URL(settings.url),
    title: {
      default:
        settings?.title ||
        "Stablo - Blog Template for Next.js & Sanity CMS",
      template: "%s | Stablo"
    },
    description:
      settings?.description ||
      "Stablo - popular open-source next.js and sanity blog template",
    keywords: ["Next.js", "Sanity", "Tailwind CSS"],
    authors: [{ name: "Surjith" }],
    canonical: settings?.url,
    openGraph: {
      images: [
        {
          url:
            urlForImage(settings?.openGraphImage)?.src ||
            "/img/opengraph.jpg",
          width: 800,
          height: 600
        }
      ]
    },
    twitter: {
      title: settings?.title || "Stablo Template",
      card: "summary_large_image"
    },
    robots: {
      index: true,
      follow: true
    }
  };
}

export async function generateMetadata({ params }) {
  return await sharedMetaData(params);
}

export default async function Layout({ children, params }) {
  const settings = await getSettings();
  return (
    <>
      <Navbar {...settings} />

      <div>{children}</div>

      <Footer {...settings} />
    </>
  );
}
```

How did you get this to work? As I said, it is basically the exact same approach as mine...
Would appreciate your feedback :)

**Comment by szriru** [comment]
I think that is a problem of the order of function execution in nextjs.
You shouldn't just put generateMetadata in root layout.js. You should put it in dynamic route page's page.js to get dynamic route's params.
My example is below. ( I put shareMetadata to lib and imported it. )
```javascript
//  app/(website)/category/[categoryName]/page.js
import CategoryPosts from "./category";
import { getPaginatedCatPosts } from "@/lib/sanity/client";
import { sharedMetaData } from "@/lib/shareMetadata";
const POSTS_PER_PAGE = 6;

export async function generateMetadata({ params }) {
  console.log("PARAMS: ", params)
  // output is PARAMS: { categoryName: 'technology' } for example
  return await sharedMetaData(params);
}

export default async function CategoryPage({ params}) {
  const category = params.categoryName;
  
  console.log(category)
  const posts = await getPaginatedCatPosts(POSTS_PER_PAGE, category);
  return <CategoryPosts posts={posts} />;
}
```

( And this is not related to this issue but i would like to suggest to author of this repo not to declare groq query params as "params" in like app/(website)/archive/archive.js in nextjs 13 app. It would confuse me for nextjs reserved "params" or useParams's params. I know its not dynamic route but it confuse me. And thank you so much for creating this template for free. )

**Comment by surjithctly** [comment]
Glad it's resolved. @szriru are you able to open a PR with your suggestions?

**Comment by szriru** [comment]
@surjithctly Thank you for your reply. Sure, I'm working on it.
