### ISSUE TITLE
Blogs not reflecting

### ISSUE THREAD

**Issue by ShivamBunge** [web3templates/stablo#50]
I deployed the template as per the instructions but I see no blogs being reflected on the hosted version
![image](https://github.com/web3templates/stablo/assets/74555699/18bdfc92-7f93-414b-af0b-c0afa18d4fe7)

When I cloned the repo locally i see this error
![image](https://github.com/web3templates/stablo/assets/74555699/50aa1ca1-594b-4484-b1c3-d8d842863c08)

I guess this is related to env variables not being properly set.

I have used .env.local.example and also tried fetching variables from vercel. Both of them arent working

**Comment by surjithctly** [comment]
You'll need to either import the demo content or add your own content before the data is even visible. 

For localhost issue, can you try upgrading next-sanity plugin to v5? `npm i next-sanity@latest`

**Comment by ShivamBunge** [comment]
@surjithctly 
Thanks.. but the demo data is added to sanity 
![image](https://github.com/web3templates/stablo/assets/74555699/9b27ccea-2485-4464-a660-4996abb83704)

still not reflecting
![image](https://github.com/web3templates/stablo/assets/74555699/ec544544-a8a1-474b-9a38-4444290618fe)

For local env
![image](https://github.com/web3templates/stablo/assets/74555699/54c4949b-9986-44ce-a5c1-78ae8cdf398d)
got this now after upgrading sanity

Data is there still postlists is empty i think.
![image](https://github.com/web3templates/stablo/assets/74555699/6bcb4f65-0a74-4bea-9fc8-72c3aad396cc)

Could both these issues indicate problem with env variables for Sanity?

**Comment by surjithctly** [comment]
Glad to hear that. 

So what happened the issue and how you resolved? It will help other people who have similar issue as well.

**Comment by ShivamBunge** [comment]
It was a dependency issue only. I checked the build logs and deleted pnpm lock file. Locally it got resolved after installing latest version of sanity mentioned in your answer.

Thank you
