### ISSUE TITLE
Unrecognized extension value in extension set ([object Object])

### ISSUE THREAD

**Issue by umitmertcakmak** [web3templates/stablo#55]
Describe the bug

When I add "Code" snippet in text editor, I get "Unrecognized extension value in extension set ([object Object])."

To Reproduce

Create a New Post
Go to "Body"
Add "Code"
See error
Error: Unrecognized extension value in extension set ([object Object]). This sometimes happens because multiple instances of @codemirror/state are loaded, breaking instanceof checks.
Error: Unrecognized extension value in extension set ([object Object]). This sometimes happens because multiple instances of @codemirror/state are loaded, breaking instanceof checks.
at inner (http://localhost:3333/node_modules/.sanity/vite/deps/chunk-LRCCG7IE.js?v=2a0fbecc:1854:15)
at inner (http://localhost:3333/node_modules/.sanity/vite/deps/chunk-LRCCG7IE.js?v=2a0fbecc:1834:9)
at inner (http://localhost:3333/node_modules/.sanity/vite/deps/chunk-LRCCG7IE.js?v=2a0fbecc:1834:9)
at inner (http://localhost:3333/node_modules/.sanity/vite/deps/chunk-LRCCG7IE.js?v=2a0fbecc:1834:9)
at inner (http://localhost:3333/node_modules/.sanity/vite/deps/chunk-LRCCG7IE.js?v=2a0fbecc:1834:9)
at flatten (http://localhost:3333/node_modules/.sanity/vite/deps/chunk-LRCCG7IE.js?v=2a0fbecc:1858:3)
at Configuration.resolve (http://localhost:3333/node_modules/.sanity/vite/deps/chunk-LRCCG7IE.js?v=2a0fbecc:1771:21)
at EditorState.create (http://localhost:3333/node_modules/.sanity/vite/deps/chunk-LRCCG7IE.js?v=2a0fbecc:2414:39)
at EditorState.fromJSON (http://localhost:3333/node_modules/.sanity/vite/deps/chunk-LRCCG7IE.js?v=2a0fbecc:2402:24)
at http://localhost:3333/node_modules/.sanity/vite/deps/CodeMirrorProxy-e83d4d37-IEJNSFB2.js?v=2a0fbecc:1812:53

Expected behavior

It should add code snippet

Which versions of Sanity are you using?

My package.json file

{
"private": true,
"scripts": {
"dev": "next dev",
"build": "next build",
"postbuild": "next-sitemap",
"start": "next start",
"sanity": "sanity dev",
"sanity-import": "sanity dataset import lib/sanity/data/production.tar.gz production",
"sanity-export": "sanity dataset export production lib/sanity/data/production.tar.gz",
"lint": "next lint"
},
"dependencies": {
"@headlessui/react": "^1.7.13",
"@heroicons/react": "^2.0.17",
"@portabletext/react": "^2.0.2",
"@sanity/code-input": "^4.1.0",
"@sanity/icons": "^2.2.2",
"@sanity/image-url": "^1.0.2",
"@sanity/table": "^1.0.1",
"@sanity/types": "^3.8.3",
"@sanity/ui": "^1.3.1",
"@sanity/vision": "^3.8.3",
"@tailwindcss/typography": "^0.5.9",
"@vercel/og": "^0.5.1",
"@web3forms/react": "^1.1.3",
"clsx": "^1.2.1",
"date-fns": "^2.29.3",
"get-video-id": "^3.6.5",
"next": "^13.3.0",
"next-sanity": "^5.1.1",
"next-seo": "^5.15.0",
"next-sitemap": "^4.0.6",
"next-themes": "^0.2.1",
"react": "^18.2.0",
"react-dom": "^18.2.0",
"react-hook-form": "^7.43.9",
"react-iframe": "^1.8.5",
"react-refractor": "^2.1.7",
"sanity": "^3.9.0",
"sanity-plugin-asset-source-unsplash": "^1.0.6",
"styled-components": "^5.3.9",
"swr": "^2.1.2",
"typescript": "^5.0.4"
},
"devDependencies": {
"autoprefixer": "^10.4.14",
"eslint": "^8.38.0",
"eslint-config-next": "^13.3.0",
"eslint-config-sanity": "^6.0.0",
"postcss": "^8.4.21",
"prettier": "^2.8.7",
"prettier-plugin-tailwindcss": "^0.2.7",
"sharp": "^0.32.0",
"tailwindcss": "^3.3.1"
}
}

What operating system are you using?

Which versions of Node.js / npm are you running?

Run npm -v && node -v in the terminal and copy-paste the result here.

9.6.7
v20.3.0

**Comment by surjithctly** [comment]
Hey, 

Can yo do a reproduction on stackblitz?

**Comment by umitmertcakmak** [comment]
I can't atm, but it started to happen on other pages such as "Settings" as I edit and publish content. I googled it but no luck so far.

**Comment by surjithctly** [comment]
Okay. Closing this issue for now. If you did not find any solution, feel free to open a new issue.
