### ISSUE TITLE
Error while trying to open the Sanity Studio

### ISSUE THREAD

**Issue by jongbu** [web3templates/stablo#59]
I created a new project using the Sanity Vercel Integration Starter options in Vercel. The frontend works fine but when I try to access the Sanity Studio, it is giving me this error "Error: Unknown handler: filter"

<img width="1401" alt="Screenshot 2023-08-20 at 9 24 08 AM" src="https://github.com/web3templates/stablo/assets/11098016/e8e26bf1-82c7-4feb-acb0-f68131318baf">

Thank you

**Comment by surjithctly** [comment]
Hey, are you visiting the Studio via http://localhost:3333 or http://localhost:3000/studio ?

Try both and see if the issue is there on both.

**Comment by jongbu** [comment]
My local works fine, the issue is in Vercel. I am not able to access the Sanity Studio in Vercel as the above error persists. Thanks

**Comment by surjithctly** [comment]
Okay, in that case do a `sanity deploy` and see if that error occurs in the studio deployed there.

**Comment by jongbu** [comment]
> Okay, in that case, run `sanity deploy` in local terminal and see if that error occurs in the studio deployed there (you will get a deployed URL).

This solves it. Thank you again

**Comment by yewyewXD** [comment]
same error on production. and on local it just keeps loading forever. the only workaround I have is to use a deployed sanity studio :/

**Comment by surjithctly** [comment]
@yewyewXD does upgrading packages help?
