### ISSUE TITLE
Issue in Build

### ISSUE THREAD

**Issue by prateekjpr20** [web3templates/stablo#61]
When I am running it in local then below error is coming 

metadata.metadataBase is not set for resolving social open graph or twitter images, using "http://localhost:3000". See https://nextjs.org/docs/app/api-reference/functions/generate-metadata#metadatabase

When I am running npm run build then this error is coming - 

Type error: Layout "app/(website)/layout.tsx" does not match the required types of a Next.js Layout.  "sharedMetaData" is not a valid Layout export field.

When I am seeing app/(website)/layout.tsx then this line is commented. Do I need to enter something here?
    // metadataBase: new URL(settings.url),

Also, I am getting this warning - Sanity returns empty array. Are you sure the dataset is public? I have  double checked and my dataset is public. So I should not get this warning.

**Comment by surjithctly** [comment]
Just remove the `export`. Fixed it in the recent commit. 

```diff
- export async function sharedMetaData(params) {
+ async function sharedMetaData(params) {
```

**Comment by surjithctly** [comment]
metadataBase can be enabled to resolve opengraph images. you can either hardcode the URL or add it in sanity settings.
