### ISSUE TITLE
Image loading issue on production

### ISSUE THREAD

**Issue by prateekjpr20** [web3templates/stablo#62]
The images are not loading on my production server. 

My blog post url is 
https://finexo.in/blog/post/gst-on-sales-of-fixed-assets

The image url is coming as https://finexo.in/blog/_next/image?url=https%3A%2F%2Fcdn.sanity.io%2Fimages%2Ftb3xbyw3%2Fproduction%2Fc12fa2166c7f5cfe3b595deb7dcc11a455d521dd-1200x800.png%3Fw%3D1200%26auto%3Dformat&w=3840&q=75

And when I open this url in brower, error came - "url" parameter is not allowed

It is working fine in my local and also when I do npm run build and then npm run start.
Not getting why error is coming on server.

**Comment by surjithctly** [comment]
Did it fixed for you?
