### ISSUE TITLE
/studio/desk error on production

### ISSUE THREAD

**Issue by purplemoonit** [web3templates/stablo#63]
Hello guy! I have a problem related to CMS on production! 

I make a tutorial step-by-step and on localhost I don't have any problem (frontend/CMS) but when I deploy it (vercel) CMS is not accessible 

![Screenshot 2024-01-23 230022111](https://github.com/web3templates/stablo/assets/155559260/7b00b4c6-247c-4dc1-8fef-67230f4c8131)

any hint for this ?

**Comment by surjithctly** [comment]
I just visited the /studio path and it's working on your domain

**Comment by purplemoonit** [comment]
studio/desk isn't working gives me this type of error

**Comment by arhaanb** [comment]
Same issue for me. The route works till logging in but I get the same error when I'm on the actual dashboard. It works fine locally though

**Comment by purplemoonit** [comment]
@arhaanb I just found Slack community and questions with same issue if somebody solve it ill notice you

**Comment by surjithctly** [comment]
Fixed in this commit: https://github.com/web3templates/stablo/commit/169bf5eb2c93921cf49571d5dc567088534ed525

Update dependencies and change code in `/app/studio` folder. 

Thanks for reporting 🙏
